name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - working-directory: ./DraftCleaner
      run: npm install
    - working-directory: ./DraftCleaner
      run: npm test
      name: DraftCleaner unit tests

    - working-directory: ./GANReviewTool
      run: npm install
    - working-directory: ./GANReviewTool
      run: npm test
      name: GANReviewTool unit tests

    - working-directory: ./SpeciesHelper
      run: npm install
    - working-directory: ./SpeciesHelper
      run: npm test
      name: SpeciesHelper unit tests
    
    - working-directory: ./UserRightsDiff
      run: npm install
    - working-directory: ./UserRightsDiff
      run: npm test
      name: UserRightsDiff unit tests
    
    - working-directory: ./VoteCounter
      run: npm install
    - working-directory: ./VoteCounter
      run: npm test
      name: VoteCounter unit tests
